[package]
name = "numbat"
description = "A high precision scientific calculator with full support for physical units."
authors = ["David Peter <mail@david-peter.de>"]
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
itertools = "0.10"
num-rational = "0.4"
num-traits = "0.2"
codespan-reporting = "0.11"
strsim = "0.10.0"
pretty_dtoa = "0.3"
numbat-exchange-rates = { path = "../numbat-exchange-rates" }

[dev-dependencies]
approx = "0.5"
glob = "0.3"
