[package]
name = "numbat"
description = "A high precision scientific calculator with full support for physical units."
authors = ["David Peter <mail@david-peter.de>"]
categories = ["science", "mathematics", "parser-implementations"]
version = "1.5.0"
edition = "2021"
homepage = "https://numbat.dev/"
repository = "https://github.com/sharkdp/numbat"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
thiserror = "1"
itertools = "0.10"
num-rational = "0.4"
num-integer = "0.1.45"
num-traits = "0.2"
codespan-reporting = "0.11"
strsim = "0.10.0"
pretty_dtoa = "0.3"
numbat-exchange-rates = { version = "0.1.0", path = "../numbat-exchange-rates" }
heck = { version = "0.4.1", features = ["unicode"] }
unicode-ident = "1.0.11"
unicode-width = "0.1.10"
libc = "0.2.147"

[dev-dependencies]
approx = "0.5"
glob = "0.3"
