[package]
name = "numbat-cli"
description = "A high precision scientific calculator with full support for physical units."
authors = ["David Peter <mail@david-peter.de>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rustyline = { version = "12", features = ["derive"] }
dirs = "5"
numbat = { path = "../numbat" }
colored = "2"

[dependencies.clap]
version = "4"
features = ["suggestions", "color", "wrap_help", "derive"]

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[[bin]]
name = "numbat"
path = "src/main.rs"
