[package]
name = "numbat-cli"
authors = ["David Peter <mail@david-peter.de>"]
description = "A high precision scientific calculator with full support for physical units."
categories = ["command-line-utilities", "science", "mathematics", "parser-implementations"]
homepage = "https://numbat.dev/"
repository = "https://github.com/sharkdp/numbat"
version = "1.5.0"
edition = "2021"
readme = "../README.md"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1"
rustyline = { version = "12", features = ["derive"] }
dirs = "5"
numbat = { version = "1.5.0", path = "../numbat" }
colored = "2"
itertools = "0.10"

[dependencies.clap]
version = "4"
features = ["suggestions", "color", "wrap_help", "derive"]

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[[bin]]
name = "numbat"
path = "src/main.rs"
