[package]
name = "numbat-cli"
description = "A high precision scientific calculator with full support for physical units."
authors = ["David Peter <mail@david-peter.de>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rustyline = "10"
dirs-next = "2"
numbat = { path = "../numbat" }

[dependencies.clap]
version = "4"
features = ["suggestions", "color", "wrap_help", "derive"]

[dev-dependencies]
assert_cmd = "2"
predicates = "2"

[[bin]]
name = "numbat"
path = "src/main.rs"
