[book]
authors = ["David Peter"]
language = "en"
multilingual = false
src = "src"
title = "Numbat - scientific calculator with full support for physical units"

[output.html]
mathjax-support = true
curly-quotes = true
additional-js = ["numbat.js"]
